import { memo } from 'react';
import {
    Activity,
    AlertCircle,
    ArrowDownUp,
    ArrowRight,
    ArrowUp,
    Baby,
    BadgeCheck,
    Bandage,
    CheckCircle,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    Clock3,
    CreditCard,
    Facebook,
    FileText,
    Filter,
    Globe,
    Grid2x2,
    HeartPulse,
    Home,
    Instagram,
    Lock,
    Mail,
    MapPin,
    Menu,
    MessageCircle,
    Minus,
    PackageSearch,
    Phone,
    Pill,
    Plus,
    Search,
    Send,
    Shield,
    ShieldCheck,
    ShoppingBag,
    Sparkles,
    Star,
    Stethoscope,
    Truck,
    Trash2,
    Upload,
    X,
    Droplets,
    ShoppingCart,
    Quote,
    UserRound,
    ExternalLink,
    RefreshCw,
    Play,
    ClipboardList,
    Eye,
} from 'lucide-react';

const iconMap = {
    Activity,
    AlertCircle,
    ArrowDownUp,
    ArrowRight,
    ArrowUp,
    Baby,
    BadgeCheck,
    Bandage,
    CheckCircle,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    Clock3,
    CreditCard,
    Facebook,
    FileText,
    Filter,
    Globe,
    Grid2x2,
    HeartPulse,
    Home,
    Instagram,
    Lock,
    Mail,
    MapPin,
    Menu,
    MessageCircle,
    Minus,
    PackageSearch,
    Phone,
    Pill,
    Plus,
    Search,
    Send,
    Shield,
    ShieldCheck,
    ShoppingBag,
    Sparkles,
    Star,
    Stethoscope,
    Truck,
    Trash2,
    Upload,
    X,
    Droplets,
    ShoppingCart,
    Quote,
    UserRound,
    ExternalLink,
    RefreshCw,
    Play,
    ClipboardList,
    Eye,
};

function Icon({ name, className = 'h-5 w-5', strokeWidth = 1.75, ...props }) {
    const Component = iconMap[name];

    if (!Component) {
        return null;
    }

    return <Component className={className} strokeWidth={strokeWidth} {...props} />;
}

export default memo(Icon);
